AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Parameters:
  EnvironmentName:
    Type: String
    Default: dev
Resources:
  CreateTaskLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.CreateTaskLambda
      Runtime: java11
      Description: Create a task
      MemorySize: 512
      Timeout: 240
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        ScheduleVirtualConsultation:
          Type: Api
          Properties:
            Path: /task/create
            Method: post

  GetTaskLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.GetTaskLambda
      Runtime: java11
      Description: Get a task
      MemorySize: 512
      Timeout: 240
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        ManageAppointmentSchedule:
          Type: Api
          Properties:
            Path: /task/{taskId}
            Method: get

  UpdateTaskLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.UpdateTaskLambda
      Runtime: java11
      Description: Update task information
      MemorySize: 512
      Timeout: 240
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        MonitorElderlyParentsHealth:
          Type: Api
          Properties:
            Path: /task/update/{taskId}
            Method: post

  DeleteTaskLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ServiceLambda/build/distributions/ServiceLambda.zip
      Handler: com.kenzie.capstone.service.lambda.DeleteTaskLambda
      Runtime: java11
      Description: Delete a task
      MemorySize: 512
      Timeout: 240
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
        - AmazonS3FullAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Events:
        ReceivePrescriptionRenewals:
          Type: Api
          Properties:
            Path: /task/delete/{taskId}
            Method: post