package com.kenzie.appserver.repositories.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.kenzie.capstone.service.util.LocalDateTimeConverter;
import java.time.LocalDateTime;
import java.util.Objects;

/**
 * Represents a task record stored in the DynamoDB table "TaskManagement".
 * This class is used to map task data to DynamoDB attributes. It includes
 * fields such as task ID, title, description, assigned user, status, priority,
 * and due date. It provides getters and setters for these fields and overrides
 * the `equals` and `hashCode` methods to ensure proper comparison and hashing.
 */
@DynamoDBTable(tableName = "TaskDataStore")
public class TaskRecord {

    private String taskId;
    private String title;
    private String description;
    private String assignedTo;
    private String status;
    private String priority;
    private String taskDueDate;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @DynamoDBHashKey(attributeName = "taskId")
    @DynamoDBAutoGeneratedKey
    public String getTaskId() {
        return taskId;
    }

    @DynamoDBAttribute(attributeName = "title")
    public String getTitle() {
        return title;
    }

    @DynamoDBAttribute(attributeName = "description")
    public String getDescription() {
        return description;
    }

    @DynamoDBAttribute(attributeName = "assignedTo")
    public String getAssignedTo() {
        return assignedTo;
    }

    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    @DynamoDBAttribute(attributeName = "priority")
    public String getPriority() {
        return priority;
    }

    @DynamoDBAttribute(attributeName = "taskDueDate")
    public String getTaskDueDate() { return taskDueDate; }

    @DynamoDBAttribute(attributeName = "createdAt")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @DynamoDBAttribute(attributeName = "updatedAt")
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setAssignedTo(String assignedTo) {
        this.assignedTo = assignedTo;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public void setPriority(String priority) {
        this.priority = priority;
    }

    public void setTaskDueDate(String taskDueDate) { this.taskDueDate = taskDueDate; }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof TaskRecord)) return false;
        TaskRecord that = (TaskRecord) o;
        return Objects.equals(taskId, that.taskId) &&
                Objects.equals(title, that.title) &&
                Objects.equals(description, that.description) &&
                Objects.equals(assignedTo, that.assignedTo) &&
                Objects.equals(status, that.status) &&
                Objects.equals(priority, that.priority) &&
                Objects.equals(taskDueDate, that.taskDueDate) &&
                Objects.equals(createdAt, that.createdAt) &&
                Objects.equals(updatedAt, that.updatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(taskId, title, description, assignedTo, status, priority, taskDueDate, createdAt, updatedAt);
    }
}
